# netlify.toml

[build]
base = "client"                    # Set this if your frontend is in /client
publish = "client/dist"           # Vite outputs to dist by default
command = "npm run build"         # This will run "vite build" inside /client

[build.environment]
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
