# netlify.toml
[build]
# The directory to deploy
publish = "build"
# Build command for your site
command = "npm run build"

# Environment variables that will be applied at build time
[build.environment]
NODE_ENV = "production"

# Handle SPA routing - redirect all requests to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200